# Generated by Django 5.0 on 2023-12-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(null=True, related_name='movie_actor', to='movies.actor', verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movie_director', to='movies.actor', verbose_name='Director'),
        ),
    ]
