# Generated by Django 5.0 on 2023-12-13 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.series', verbose_name='Series'),
        ),
    ]
